from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class Router(Protocol):
    def next_hop(self, dest: str) -> str | None: ...

    async def on_info(self, pkt: dict, from_id: str) -> None: ...

    def build_local_info(self) -> dict | None: ...

    def recompute(self) -> None: ...
